// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guxewmpocounzgrgklsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1eGV3bXBvY291bnpncmdrbHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNjczMzQsImV4cCI6MjA2Mjg0MzMzNH0.DFOf4ldA-LikxmvCI50m5Ttdz3rIMCNLcTniSsDFE9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);